"""
This contains Pydantic models for the bits and pieces of the Narrative method specs.
These are assembled from the MethodSpec object in the Narrative Method Store here:
https://github.com/kbase/narrative_method_store/blob/6b371d3697a8eae59e2899624f5ca5091e056340/NarrativeMethodStore.spec#L616

The "method" names were converted to "app" because "method" is the old way, and we use
app as the semantic term everywhere else these days.

Also note that this era of KBase was (still is...) a wild place, so most of these fields
are optional.

Primary usage:
get app spec from NMS
spec = nms.get_app_spec("app_name")

convert
app_spec = AppSpec(**spec)

Now it's a model and can be used as such. Useful for validations and inputs to
various LLM agent functions.
"""

from typing import Any
from pydantic import BaseModel


class Icon(BaseModel):
    url: str


class AppBriefInfo(BaseModel):
    id: str
    module_name: str | None = None
    git_commit_hash: str | None = None
    name: str
    ver: str
    subtitle: str
    tooltip: str
    categories: list[str]
    loading_error: str | None = None
    authors: list[str]
    input_types: list[str]
    output_types: list[str]
    app_type: str
    icon: Icon | None = None


class WidgetSpec(BaseModel):
    input: str | None = None
    output: str | None = None


class RegexMatcher(BaseModel):
    regex: str
    error_text: str
    match: int  # bool


class TextOptions(BaseModel, extra="ignore"):
    valid_ws_types: list[str] | None = None
    validate_as: str | None = None
    is_output_name: int = 0  # bool
    placeholder: str | None = None
    min_int: int | None = None
    max_int: int | None = None
    min_float: float | None = None
    max_float: float | None = None
    regex_constraint: list[RegexMatcher] | None = None


class TextAreaOptions(BaseModel):
    n_rows: int
    placeholder: str


class IntSliderOptions(BaseModel):
    min: int
    max: int
    step: int


class FloatSliderOptions(BaseModel):
    min: float
    max: float


class CheckboxOptions(BaseModel):
    checked_value: int  # bool
    unchecked_value: int  # bool


class DropdownOption(BaseModel):
    value: str
    display: str


class DropdownOptions(BaseModel):
    options: list[DropdownOption]
    multiselection: int = 0  # bool


class DynamicDropdownOptions(BaseModel):
    data_source: str
    service_function: str | None = None
    service_version: str | None = None
    service_params: Any
    selection_id: str | None = None
    exact_match_on: str | None = None
    description_template: str | None = None
    multiselection: int  # bool
    query_on_empty_input: int  # bool
    result_array_index: int
    path_to_selection_items: list[str] | None = None


class RadioOptions(BaseModel):
    id_order: list[str]
    ids_to_options: dict[str, str]
    ids_to_tooltip: dict[str, str]


class TabOptions(BaseModel):
    tab_id_order: list[str]
    tab_id_to_tab_name: dict[str, str]
    tab_id_to_param_ids: dict[str, list[str]]


class SubdataSelection(BaseModel):
    constant_ref: list[str] | None = None
    parameter_id: str
    subdata_included: list[str]
    path_to_subdata: list[str]
    selection_id: str | None = None
    selection_description: list[str] | None = None
    description_template: str | None = None
    service_function: str | None = None
    service_version: str | None = None


class TextSubdataOptions(BaseModel):
    placeholder: str
    multiselection: int  # bool
    show_src_obj: int  # bool
    allow_custom: int  # bool
    subdata_selection: SubdataSelection


class AppParameter(BaseModel):
    id: str
    ui_name: str
    short_hint: str
    description: str
    field_type: str
    allow_multiple: int  # bool
    optional: int  # bool
    advanced: int  # bool
    disabled: int  # bool
    default_values: list[str] | None = []
    ui_class: str
    valid_file_types: list[str] | None = None

    text_options: TextOptions | None = None
    textarea_options: TextAreaOptions | None = None
    intslider_options: IntSliderOptions | None = None
    floatslider_options: FloatSliderOptions | None = None
    checkbox_options: CheckboxOptions | None = None
    dropdown_options: DropdownOptions | None = None
    dynamic_dropdown_options: DynamicDropdownOptions | None = None
    radio_options: RadioOptions | None = None
    tab_options: TabOptions | None = None
    textsubdata_options: TextSubdataOptions | None = None


class FixedAppParameter(BaseModel):
    ui_name: str
    description: str


class AppParameterGroup(BaseModel):
    id: str
    parameter_ids: list[str]
    ui_name: str
    short_hint: str
    description: str
    allow_multiple: int  # bool
    optional: int  # bool
    advanced: int  # bool
    with_border: int  # bool
    id_mapping: dict[str, str] | None = None


class AutoGeneratedValue(BaseModel):
    prefix: str | None = None
    symbols: int | None = None
    suffix: str | None = None


class ServiceInputMapping(BaseModel):
    input_parameter: str | None = None
    constant_value: Any | None = None
    narrative_system_variable: str | None = None
    generated_value: AutoGeneratedValue | None = None
    target_argument_position: int | None = None
    target_property: str | None = None
    target_type_transform: str | None = None


class ServiceOutputMapping(BaseModel):
    input_parameter: str | None = None
    service_method_output_path: list[str] | None = None
    constant_value: Any | None = None
    narrative_system_variable: str | None = None
    target_property: str | None = None
    target_type_transform: str | None = None


class OutputMapping(BaseModel):
    input_parameter: str | None = None
    constant_value: Any | None = None
    narrative_system_variable: str | None = None
    target_property: str | None = None
    target_type_transform: str | None = None


class AppBehavior(BaseModel):
    kb_service_url: str | None = None
    kb_service_name: str | None = None
    kb_service_version: str | None = None
    kb_service_method: str | None = None
    resource_estimator_module: str | None = None
    resource_estimator_method: str | None = None
    kb_service_input_mapping: list[ServiceInputMapping] | None = None
    kb_service_output_mapping: list[ServiceOutputMapping] | None = None
    output_mapping: list[OutputMapping] | None = None


class AppSpec(BaseModel):
    info: AppBriefInfo
    widgets: WidgetSpec
    parameters: list[AppParameter] | None = None
    fixed_parameters: list[FixedAppParameter] | None = None
    parameter_groups: list[AppParameterGroup] | None = None
    behavior: AppBehavior
    job_id_output_field: str | None = None
    replacement_text: str | None = None
