[tool.poetry]
name = "narrative-llm-agent"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "narrative_llm_agent"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
langchain = "^0.1.3"
crewai = "0.16.3"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pytest-cov = "^4.1.0"
pytest-mock = "^3.12.0"
requests-mock = "^1.11.0"
ruff = "^0.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--import-mode=importlib --cov=narrative_llm_agent -s --verbose --cov-report html --cov-report term"

[tool.ruff]
line-length = 100

# E203: whitespace before ‘,’, ‘;’, or ‘:’
# E501: line length
lint.ignore = [
    "E203",
    "E501"
]

# Exclude a variety of commonly ignored directories.
exclude = [
    "__pypackages__",
    "_build",
    ".bzr",
    ".direnv",
    ".eggs",
    ".git-rewrite",
    ".git",
    ".github",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "*.pyc",
    "buck-out",
    "build",
    "deps",
    "dist",
    "node_modules",
    "other_schema",
    "python-coverage",
    "sample_data",
    "venv",
]

[tool.ruff.format]
quote-style = "double"
