[tool.poetry]
name = "narrative-llm-agent"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "narrative_llm_agent"}]

[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.1.3"
crewai = "^0.1.32"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
pytest-cov = "^4.1.0"
pytest-mock = "^3.12.0"
requests-mock = "^1.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--import-mode=importlib --cov=narrative_llm_agent -s --verbose"
